### ISSUE TITLE
Research AR vs VR

### ISSUE THREAD

**Issue by edogdu** [edogdu/RAM_Cyber_Defenders#1]

**Comment by Luk-Er4** [comment]
To develop VR games with our Meta Quest 2, I found that we need to put our devices into developer mode. However, I couldn't do so. I guess probably some of our devices are not allowed to do it.
  I got an error message and it says "This headset is already connected to a Meta Account. You will need to factory reset the headset to set it up with your account." Here is my thought about this happening.
  I think someone already used and connected the device to their own Meta account for their previous project, so that is why I cannot connect my device to developer mode. So there are two ways to deal with this. 
  One way is that people who did their research before should disconnect the devices with their Meta account. Or the other way is that we can do a factory reset(device reset) so that we can get access to our devices to our Meta account.

  Maybe I thought wrong or had a misconception about this situation, but I hope it might help to take our studies to the next step.

**Comment by edogdu** [comment]
Let's talk to IT about this. It is not used for development before. This is the first time. So, IT account should be fine for development, but I am not sure. Let's talk tomorrow after class briefly. Thanks for researching this.

**Comment by LightTheBlues** [comment]
Hi. Dr.Dogdu

You mentioned you want to meet tomorrow after class however I am not in
your section and I don't know when was the class over. Do you like me to
attend as well or I will just meet you Friday during office hours?

**Comment by Luk-Er4** [comment]
Here is another difficulty that I encountered in trying to develop VR games on campus. 

In order to develop VR games, we need Unity and Oculus applications on a computer. Also, depending on our needs, we might need to download another version. (I will write a comment on my unity version suggestion.)

So I visited the computer lab, and I tried to download the Oculus application, and another version of Unity since Unity Learn suggested to do so. However, whenever I tried to download, I needed an administrator's access to do so. So I could not download them and stopped doing it. This problem has to be dealt with as well to proceed with our project.
