### ISSUE TITLE
Which Unity version?

### ISSUE THREAD

**Issue by edogdu** [edogdu/RAM_Cyber_Defenders#3]

**Comment by Luk-Er4** [comment]
Here is my suggestion for the Unity version.

I thought using the LTS(Long-Term Supported) Unity version is much better for our project since the LTS version of Unity got or gets fully supported for two years, which means that we can develop games in a stable environment. 2020.3, 2021.3, and 2022.3 are the LTS version. 

However, there are a lot of comments about the 2022.3 LTS version that developers are having problems with serious frame drops when testing their VR games. Considering that, 2020.3 LTS or 2021.3 LTS are good options. 

2021.3 LTS might be the best, but the VR game dev course in Unity Learn uses 2020.3 LTS. 2020.3 LTS would be good because Unity Learn offers good quality courses and we can just implement the knowledge to that version. But if we can catch up on the steps to develop VR games quickly, 2021.3 LTS is also perfect.

**Comment by LightTheBlues** [comment]
During class and probably every computer in the computer lab either uses 2020.3.12f1 or older. If we choose to upgrade Unity to version 2021.3, then we will have to upgrade them in the computer lab. Based on my research, it seems like 2020.3 LTS is more stable compared to 2021.3 (this may have been improved, as the responses I found were from 2022 or older).

Unity 2020.3 LTS has also reached the end of Unity's two-year Long-Term Support, and Microsoft XR Mixed Reality recommends using the 2021.3 version as it supports the newest features (if we would like our game to be compatible with other devices). Even though I found reasons to use 2022.3, I think it's safer to go with a more stable version of Unity (2020.3 or 2021.3).

I was able to launch the XR Plugin Manager on the Unity version we use in the lab (2020.3.12f1), so I am confident that this version could be fine for our projects. However, if we would like Unity to support, maybe we can upgrade to 2021.3, which I would be fine using either version.

I also created a test scene under 2020.3.12f1 where I installed the XR Interaction Toolkit and its Starter Assets. It seems to be functional, but I may require an actual VR device to test it out. I may need to borrow one from school in order to conduct thorough testing.
